#ifndef GOB_UDF_PERMEABILITY_H
#define GOB_UDF_PERMEABILITY_H

/*
	-------------------------------------------------
	!   Permeability or in FLUENT the inverse of    !
	!   makes RESISTANCE profiles                   !
	!   One for each direction 1,2,3 or x,y,x       !
	!   and one for each fluid zone                 !
	!                                               !
	!   STORES in (user-define-memory 0)            !
	!				udm-0           !
	!-----------------------------------------------!
*/

#define define_permeability_1()                                                                                                                                                                                                                                                                                                                                                                                            \
	({                                                                                                                                                                                                                                                                                                                                                                                                                 \
		/* FLUENT allows for an inertial resistance parameter to account for turbulent and transitional flow. Inertial resistance can be found using the following equation ANSYS (2010): C2 = 3.5 / d * (1-n)/ n^3 where d is the mean particle diameter (meters) and n is the porosity (%) of the medium. This equation is valid for use in the momentum conservation equation used by Ansys, Inc. in FLUENT. */ \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		real x[ND_ND]; /* position vector x[0]=x, x[1]=y, x[2]=z */                                                                                                                                                                                                                                                                                                                                                \
		cell_t c;                                                                                                                                                                                                                                                                                                                                                                                                  \
		real cellporo;                                                                                                                                                                                                                                                                                                                                                                                             \
		real initial_permeability;                                                                                                                                                                                                                                                                                                                                                                                 \
		real cellresist;                                                                                                                                                                                                                                                                                                                                                                                           \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		real V_v = 0.40000000;                                                                                                                                                                                                                                                                                                                                                                                     \
		real a = 1;                                                                                                                                                                                                                                                                                                                                                                                                \
		real resist_scaler = 1;                                                                                                                                                                                                                                                                                                                                                                                    \
		real maximum_resist = 5.000000E6;                                                                                                                                                                                                                                                                                                                                                                          \
		real minimum_resist = 1.45000E5; /* equals 6.91e-6 1/m2 permeability */                                                                                                                                                                                                                                                                                                                                    \
		if (RP_Variable_Exists_P(                                                                                                                                                                                                                                                                                                                                                                                  \
			    "longwallgobs/max_porosity")) { /* Get scheme variable and assign it if it exists */                                                                                                                                                                                                                                                                                                           \
			V_v = (RP_Get_Real("longwallgobs/max_porosity"));                                                                                                                                                                                                                                                                                                                                                  \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/initial_porosity")) {                                                                                                                                                                                                                                                                                                                                               \
			a = (RP_Get_Real("longwallgobs/initial_porosity"));                                                                                                                                                                                                                                                                                                                                                \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/resist_scaler")) {                                                                                                                                                                                                                                                                                                                                                  \
			resist_scaler = (RP_Get_Real("longwallgobs/resist_scaler"));                                                                                                                                                                                                                                                                                                                                       \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/max_resistance")) {                                                                                                                                                                                                                                                                                                                                                 \
			maximum_resist = (RP_Get_Real("longwallgobs/max_resistance"));                                                                                                                                                                                                                                                                                                                                     \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/min_resistance")) {                                                                                                                                                                                                                                                                                                                                                 \
			minimum_resist = (RP_Get_Real("longwallgobs/min_resistance"));                                                                                                                                                                                                                                                                                                                                     \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		initial_permeability = Initial_Perm();                                                                                                                                                                                                                                                                                                                                                                     \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		begin_c_loop(c, t)                                                                                                                                                                                                                                                                                                                                                                                         \
		{                                                                                                                                                                                                                                                                                                                                                                                                          \
			C_CENTROID(x, c, t);                                                                                                                                                                                                                                                                                                                                                                               \
			if (ite <= 1) {                                                                                                                                                                                                                                                                                                                                                                                    \
				cellporo = ((V_v - C_UDMI(c, t, 4)) * a < 0) ?                                                                                                                                                                                                                                                                                                                                             \
						   0 :                                                                                                                                                                                                                                                                                                                                                                     \
						   (V_v - C_UDMI(c, t, 4)) *                                                                                                                                                                                                                                                                                                                                               \
							   a; /* Limit lowest value of porosity to zero */                                                                                                                                                                                                                                                                                                                 \
				cellresist = Cell_Resistance(cellporo,                                                                                                                                                                                                                                                                                                                                                     \
							     initial_permeability); /* Carmen-Kozeny Relationship */                                                                                                                                                                                                                                                                                                       \
				/* Limit MAX and MIN resistance */                                                                                                                                                                                                                                                                                                                                                         \
				if (cellresist < maximum_resist) {                                                                                                                                                                                                                                                                                                                                                         \
					if (cellresist < minimum_resist) {                                                                                                                                                                                                                                                                                                                                                 \
						cellresist = minimum_resist;                                                                                                                                                                                                                                                                                                                                               \
					}                                                                                                                                                                                                                                                                                                                                                                                  \
				} else {                                                                                                                                                                                                                                                                                                                                                                                   \
					cellresist = maximum_resist;                                                                                                                                                                                                                                                                                                                                                       \
				}                                                                                                                                                                                                                                                                                                                                                                                          \
				C_PROFILE(c, t, nv) =                                                                                                                                                                                                                                                                                                                                                                      \
					cellresist * resist_scaler; /* Scaler applied to cell resistance */                                                                                                                                                                                                                                                                                                                \
				C_UDMI(c, t, 0) = cellresist * resist_scaler;                                                                                                                                                                                                                                                                                                                                              \
			}                                                                                                                                                                                                                                                                                                                                                                                                  \
			if (ite > 1) {                                                                                                                                                                                                                                                                                                                                                                                     \
				C_PROFILE(c, t, nv) = C_UDMI(c, t, 0);                                                                                                                                                                                                                                                                                                                                                     \
			}                                                                                                                                                                                                                                                                                                                                                                                                  \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		end_c_loop(c, t);                                                                                                                                                                                                                                                                                                                                                                                          \
		void;                                                                                                                                                                                                                                                                                                                                                                                                      \
	})

#define define_permeability_2()                                                                                                                                                                                                                                                                                                                                                                                            \
	({                                                                                                                                                                                                                                                                                                                                                                                                                 \
		/* FLUENT allows for an inertial resistance parameter to account for turbulent and transitional flow. Inertial resistance can be found using the following equation ANSYS (2010): C2 = 3.5 / d * (1-n)/ n^3 where d is the mean particle diameter (meters) and n is the porosity (%) of the medium. This equation is valid for use in the momentum conservation equation used by Ansys, Inc. in FLUENT. */ \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		real x[ND_ND]; /* position vector x[0]=x, x[1]=y, x[2]=z */                                                                                                                                                                                                                                                                                                                                                \
		cell_t c;                                                                                                                                                                                                                                                                                                                                                                                                  \
		real cellporo;                                                                                                                                                                                                                                                                                                                                                                                             \
		real initial_permeability;                                                                                                                                                                                                                                                                                                                                                                                 \
		real cellresist;                                                                                                                                                                                                                                                                                                                                                                                           \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		real V_v = 0.40000000;                                                                                                                                                                                                                                                                                                                                                                                     \
		real a = 1;                                                                                                                                                                                                                                                                                                                                                                                                \
		real resist_scaler = 1;                                                                                                                                                                                                                                                                                                                                                                                    \
		real maximum_resist = 5.000000E6;                                                                                                                                                                                                                                                                                                                                                                          \
		real minimum_resist = 1.45000E5; /* equals 6.91e-6 1/m2 permeability */                                                                                                                                                                                                                                                                                                                                    \
		if (RP_Variable_Exists_P(                                                                                                                                                                                                                                                                                                                                                                                  \
			    "longwallgobs/max_porosity")) { /* Get scheme variable and assign it if it exists */                                                                                                                                                                                                                                                                                                           \
			V_v = (RP_Get_Real("longwallgobs/max_porosity"));                                                                                                                                                                                                                                                                                                                                                  \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/initial_porosity")) {                                                                                                                                                                                                                                                                                                                                               \
			a = (RP_Get_Real("longwallgobs/initial_porosity"));                                                                                                                                                                                                                                                                                                                                                \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/resist_scaler")) {                                                                                                                                                                                                                                                                                                                                                  \
			resist_scaler = (RP_Get_Real("longwallgobs/resist_scaler"));                                                                                                                                                                                                                                                                                                                                       \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/max_resistance")) {                                                                                                                                                                                                                                                                                                                                                 \
			maximum_resist = (RP_Get_Real("longwallgobs/max_resistance"));                                                                                                                                                                                                                                                                                                                                     \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/min_resistance")) {                                                                                                                                                                                                                                                                                                                                                 \
			minimum_resist = (RP_Get_Real("longwallgobs/min_resistance"));                                                                                                                                                                                                                                                                                                                                     \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		initial_permeability = Initial_Perm();                                                                                                                                                                                                                                                                                                                                                                     \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		begin_c_loop(c, t)                                                                                                                                                                                                                                                                                                                                                                                         \
		{                                                                                                                                                                                                                                                                                                                                                                                                          \
			C_CENTROID(x, c, t);                                                                                                                                                                                                                                                                                                                                                                               \
			if (ite <= 1) {                                                                                                                                                                                                                                                                                                                                                                                    \
				cellporo = ((V_v - C_UDMI(c, t, 4)) * a < 0) ?                                                                                                                                                                                                                                                                                                                                             \
						   0 :                                                                                                                                                                                                                                                                                                                                                                     \
						   (V_v - C_UDMI(c, t, 4)) *                                                                                                                                                                                                                                                                                                                                               \
							   a; /* Limit lowest value of porosity to zero */                                                                                                                                                                                                                                                                                                                 \
				cellresist = Cell_Resistance(cellporo,                                                                                                                                                                                                                                                                                                                                                     \
							     initial_permeability); /* Carmen-Kozeny Relationship */                                                                                                                                                                                                                                                                                                       \
				/* Limit MAX and MIN resistance */                                                                                                                                                                                                                                                                                                                                                         \
				if (cellresist < maximum_resist) {                                                                                                                                                                                                                                                                                                                                                         \
					if (cellresist < minimum_resist) {                                                                                                                                                                                                                                                                                                                                                 \
						cellresist = minimum_resist;                                                                                                                                                                                                                                                                                                                                               \
					}                                                                                                                                                                                                                                                                                                                                                                                  \
				} else {                                                                                                                                                                                                                                                                                                                                                                                   \
					cellresist = maximum_resist;                                                                                                                                                                                                                                                                                                                                                       \
				}                                                                                                                                                                                                                                                                                                                                                                                          \
				C_PROFILE(c, t, nv) =                                                                                                                                                                                                                                                                                                                                                                      \
					cellresist * resist_scaler; /* Scaler applied to cell resistance */                                                                                                                                                                                                                                                                                                                \
				C_UDMI(c, t, 0) = cellresist * resist_scaler;                                                                                                                                                                                                                                                                                                                                              \
			}                                                                                                                                                                                                                                                                                                                                                                                                  \
			if (ite > 1) {                                                                                                                                                                                                                                                                                                                                                                                     \
				C_PROFILE(c, t, nv) = C_UDMI(c, t, 0);                                                                                                                                                                                                                                                                                                                                                     \
			}                                                                                                                                                                                                                                                                                                                                                                                                  \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		end_c_loop(c, t);                                                                                                                                                                                                                                                                                                                                                                                          \
		void;                                                                                                                                                                                                                                                                                                                                                                                                      \
	})

#define define_permeability_3()                                                                                                                                                                                                                                                                                                                                                                                            \
	({                                                                                                                                                                                                                                                                                                                                                                                                                 \
		/* FLUENT allows for an inertial resistance parameter to account for turbulent and transitional flow. Inertial resistance can be found using the following equation ANSYS (2010): C2 = 3.5 / d * (1-n)/ n^3 where d is the mean particle diameter (meters) and n is the porosity (%) of the medium. This equation is valid for use in the momentum conservation equation used by Ansys, Inc. in FLUENT. */ \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		real x[ND_ND]; /* position vector x[0]=x, x[1]=y, x[2]=z */                                                                                                                                                                                                                                                                                                                                                \
		cell_t c;                                                                                                                                                                                                                                                                                                                                                                                                  \
		real cellporo;                                                                                                                                                                                                                                                                                                                                                                                             \
		real initial_permeability;                                                                                                                                                                                                                                                                                                                                                                                 \
		real cellresist;                                                                                                                                                                                                                                                                                                                                                                                           \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		real V_v = 0.40000000;                                                                                                                                                                                                                                                                                                                                                                                     \
		real a = 1;                                                                                                                                                                                                                                                                                                                                                                                                \
		real resist_scaler = 1;                                                                                                                                                                                                                                                                                                                                                                                    \
		real maximum_resist = 5.000000E6;                                                                                                                                                                                                                                                                                                                                                                          \
		real minimum_resist = 1.45000E5; /* equals 6.91e-6 1/m2 permeability */                                                                                                                                                                                                                                                                                                                                    \
		if (RP_Variable_Exists_P(                                                                                                                                                                                                                                                                                                                                                                                  \
			    "longwallgobs/max_porosity")) { /* Get scheme variable and assign it if it exists */                                                                                                                                                                                                                                                                                                           \
			V_v = (RP_Get_Real("longwallgobs/max_porosity"));                                                                                                                                                                                                                                                                                                                                                  \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/initial_porosity")) {                                                                                                                                                                                                                                                                                                                                               \
			a = (RP_Get_Real("longwallgobs/initial_porosity"));                                                                                                                                                                                                                                                                                                                                                \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/resist_scaler")) {                                                                                                                                                                                                                                                                                                                                                  \
			resist_scaler = (RP_Get_Real("longwallgobs/resist_scaler"));                                                                                                                                                                                                                                                                                                                                       \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/max_resistance")) {                                                                                                                                                                                                                                                                                                                                                 \
			maximum_resist = (RP_Get_Real("longwallgobs/max_resistance"));                                                                                                                                                                                                                                                                                                                                     \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		if (RP_Variable_Exists_P("longwallgobs/min_resistance")) {                                                                                                                                                                                                                                                                                                                                                 \
			minimum_resist = (RP_Get_Real("longwallgobs/min_resistance"));                                                                                                                                                                                                                                                                                                                                     \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		initial_permeability = Initial_Perm();                                                                                                                                                                                                                                                                                                                                                                     \
                                                                                                                                                                                                                                                                                                                                                                                                                           \
		begin_c_loop(c, t)                                                                                                                                                                                                                                                                                                                                                                                         \
		{                                                                                                                                                                                                                                                                                                                                                                                                          \
			C_CENTROID(x, c, t);                                                                                                                                                                                                                                                                                                                                                                               \
			if (ite <= 1) {                                                                                                                                                                                                                                                                                                                                                                                    \
				cellporo = ((V_v - C_UDMI(c, t, 4)) * a < 0) ?                                                                                                                                                                                                                                                                                                                                             \
						   0 :                                                                                                                                                                                                                                                                                                                                                                     \
						   (V_v - C_UDMI(c, t, 4)) *                                                                                                                                                                                                                                                                                                                                               \
							   a; /* Limit lowest value of porosity to zero */                                                                                                                                                                                                                                                                                                                 \
				cellresist = Cell_Resistance(cellporo,                                                                                                                                                                                                                                                                                                                                                     \
							     initial_permeability); /* Carmen-Kozeny Relationship */                                                                                                                                                                                                                                                                                                       \
				/* Limit MAX and MIN resistance */                                                                                                                                                                                                                                                                                                                                                         \
				if (cellresist < maximum_resist) {                                                                                                                                                                                                                                                                                                                                                         \
					if (cellresist < minimum_resist) {                                                                                                                                                                                                                                                                                                                                                 \
						cellresist = minimum_resist;                                                                                                                                                                                                                                                                                                                                               \
					}                                                                                                                                                                                                                                                                                                                                                                                  \
				} else {                                                                                                                                                                                                                                                                                                                                                                                   \
					cellresist = maximum_resist;                                                                                                                                                                                                                                                                                                                                                       \
				}                                                                                                                                                                                                                                                                                                                                                                                          \
				C_PROFILE(c, t, nv) =                                                                                                                                                                                                                                                                                                                                                                      \
					cellresist * resist_scaler; /* Scaler applied to cell resistance */                                                                                                                                                                                                                                                                                                                \
				C_UDMI(c, t, 0) = cellresist * resist_scaler;                                                                                                                                                                                                                                                                                                                                              \
			}                                                                                                                                                                                                                                                                                                                                                                                                  \
			if (ite > 1) {                                                                                                                                                                                                                                                                                                                                                                                     \
				C_PROFILE(c, t, nv) = C_UDMI(c, t, 0);                                                                                                                                                                                                                                                                                                                                                     \
			}                                                                                                                                                                                                                                                                                                                                                                                                  \
		}                                                                                                                                                                                                                                                                                                                                                                                                          \
		end_c_loop(c, t);                                                                                                                                                                                                                                                                                                                                                                                          \
		void;                                                                                                                                                                                                                                                                                                                                                                                                      \
	})

#endif // GOB_UDF_PERMEABILITY_H
